[project]
name = "gomata-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "googletrans>=4.0.2",
    "manga-ocr>=0.1.14",
    "pillow>=11.1.0",
    "pyqt6>=6.8.0",
]
